### ISSUE TITLE
Responsive home

### ISSUE THREAD

**Issue by gonzalobonini** [jschwindt/Venganzas-del-Pasado#12]
Juan, muy buen trabajo con el sitio, realmente muy bueno. Algo que estaría bueno contemplar es hacer responsive el home para que sea mas fácil ingresar desde dispositivos móviles, puedo ayudar con eso si hiciera falta.

**Comment by jschwindt** [comment]
Hace ya varios meses que es responsive, recién me doy cuenta de cerrar este ticket.
