### ISSUE TITLE
Sound quality / calidad del sonido

### ISSUE THREAD

**Issue by wehlutyk** [jschwindt/Venganzas-del-Pasado#13]
Primero bravo y gracias por la súper página! Escucho el programa bastante seguido y me pregunto si no podemos obtener una grabación de mejor calidad.

El [stream del script cron](https://github.com/jschwindt/Venganzas-del-Pasado/blob/master/script/radio-del-plata.sh#L12) es de 64kbps, y no encontré otro mejor. Dónde lo encontraron a éste? ([el que da TuneIn](http://tunein.com/radio/Radio-del-Plata-1030-s25853/) es el mismo -- lo encontraron ahí?). Tendría sentido escribir a la radio preguntando si no pueden dar un live con bitrate más alto?

**Comment by jschwindt** [comment]
Hola @wehlutyk!

El stream es del sitio oficial http://www.amdelplata.com/. No creo que se vayan a preocupar en darnos un stream mejor exclusivamente para nosotros :(

Por otro lado, mejorar la calidad probablemente implique aumentar el tamaño del archivo, y con miles de descargas por día eso implica aumentar el ancho de banda, y ahora llego picos de 70Mbps y el máximo que tengo es 100Mbps.

Saludos,
Juan.

**Comment by wehlutyk** [comment]
Entendido, gracias por la respuesta :)

**Comment by facastagnini** [comment]
Che perdón que me meta en un tread cerrado, pero llegué acá porque quiero tener un mirror de los audios. Un problema que tenemos con los episodios muy viejos (anteriores a VDP) es que la calidad es muy mala, y me preguntno si en el futuro nos vamos a arrepentir de no grabar una copia de archivo con mayor calidad.

Que les parece si hacemos un segudo archivo en flac para poder volver a estos audios mas adelante?

Otra pregunta relativamente relacionada con esto es sobre mirrors,  tenemos mas de un server bajando el streaming? Hay mas de una copia de los audios?

**Comment by jschwindt** [comment]
Hola Federico! Te voy respondiendo a cada punto:

1. Post anteriores a VDP: los suben los usuarios y en general provienen de digitalizar viejos cassettes, no creo que se pueda hacer mucho más con la calidad.
2. Flac: no sé cuál sería la ganancia de usar un formato Lossless. Todo lo que se graba en vivo proviene del streaming de la radio, que ya de por sí es de baja calidad. Después yo lo reencodeo para nivelar un poco el volumen y tratar de mejorarlo un poco.
3. Los archivos ocupan alrededor de 20MB y ya hay un backup de cada uno en Amazon S3. De hecho el torrent te lo baja directamente de S3.
4. Hay un sólo server que baja varios streamings de distintas radios al mismo tiempo, pero lamentablemente suelen interrumpirse, por lo que últimamente los más confiable es tomarlo de RadioCut. Si tenés posibilidad de grabar vos en otro server, yo tengo todo preparado para bajarlo por HTTP y generar el post a partir de eso cuando el principal falla.

Gracias por preocuparte y de más está decir que cualquier ayuda es bienvenida.

Juan.

**Comment by facastagnini** [comment]
Me queda claro, si no existe un stream de mayor calidad no tiene sentido.

Juan, descargo el podcast todos los días desde tu sitio hace años, quiero darte una mano.
Te puedo ayudar con temas de infraestructura. Tengo esa NAS con un backup offsite y puedo dedicar una virtual para tener un segundo nodo de descarga. Te puedo ayudar a bancar el hosting.
Decime como puedo colaborar. 

Gracias!

**Comment by jpdborgna** [comment]
Estoy en la misma, me sumo.

--

*Juan Pablo Daniel Borgna*+44 7708 024804 @jpdborgna
<https://twitter.com/jpdborgna> LinkedIn
<http://www.linkedin.com/in/jpdborgna>

2016-05-17 1:38 GMT+01:00 Federico Castagnini <notifications@github.com>:

**Comment by jschwindt** [comment]
Gracias muchachos, cualquier cosa les aviso. Por ahora el sitio funciona casi solo y no tengo que dedicarle mucho tiempo. Por el lado del hosting, tengo un server dedicado acá: http://www.kimsufi.com/us/en/servers.xml que además me da 100Mbps de ancho de banda. El costo de esto + Amazon S3 está cubierto por lo que ingresa de publicidad.
