### ISSUE TITLE
[FEATURE REQUEST] Audio opcional sin tandas publicitarias/noticias ni segmento musical

### ISSUE THREAD

**Issue by elcosomalo1** [jschwindt/Venganzas-del-Pasado#35]
Agregar la opcion para descargar el audio del programa sin el segmento musical ni las tandas publicitarias.
Un ejemplo de esto se puede encontrar en el canal de youtube "comunidad vengadora": https://www.youtube.com/channel/UCRnkHsD3k8HyymKJzsM_UpA

Una manera que se me ocurre para automatizar esto es grabar por horarios aunque esto seria imperfecto es la unica manera que se me ocurre de realizar este trabajo, grabando segmentos en bloques horarios y luego uniendolos todos automaticamente para generar un programa sin las tandas ni el segmento musical.

**Comment by jschwindt** [comment]
Otra posibilidad es tomar el audio del video de youtube de esta "comunidad vengadora", lo voy a analizar y tal vez agregarlo como opción. ¡Gracias!

**Comment by elcosomalo1** [comment]
> Otra posibilidad es tomar el audio del video de youtube de esta "comunidad vengadora", lo voy a analizar y tal vez agregarlo como opción. ¡Gracias!

Es una buena opcion... pero tendrias que editarlo un poco porque este muchacho de "comunidad vengadora" le pone una musica al final de cada video que resulta un poco molesta. A lo mejor (se me ocurre) que se podria contar aprox el tiempo de esta "musica del final" de atras para adelante y si el tiempo coincide en todos los videos, se podria remover de manera automatica con alguna herramienta de audio.

Saludos!

**Comment by jschwindt** [comment]
¡Hecho! Fijate qué te parece, quedó todo automatizado ;-)

**Comment by elcosomalo1** [comment]
> ¡Hecho! Fijate qué te parece, quedó todo automatizado...

Genio! quedó perfecto!
